FIELD_PROMPT = "prompt"
FIELD_STYLE = "style"
FIELD_STATUS = "status"
FIELD_IMAGE_URL = "image_url"
FIELD_CREATED_AT = "created_at"
FIELD_UPDATED_AT = "updated_at"

STATUS_QUEUED = "queued"
STATUS_PROCESSING = "processing"
STATUS_COMPLETED = "completed"
STATUS_FAILED = "failed"
